# Datos de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgresdb
spring.datasource.username=postgres
spring.datasource.password=tu_contraseña

# Estrategia de Hibernate (update creará las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto para PostgreSQL 16
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Forzar a Hibernate a usar Jackson para los campos JSONB
spring.jpa.properties.hibernate.type.json_format_mapper=org.hibernate.type.format.jackson.JacksonJsonFormatMapper

# Limites de subida para Multimedia y Documentos 
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# Configuración SMTP RieDental
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu-correo@gmail.com
spring.mail.password=tu-contraseña-de-aplicacion-de-google
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true